name: auropay
description: payment service
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  charts_flutter: ^0.12.0
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  flutter_svg: ^1.1.6
  country_icons: ^2.0.2
  path_provider: ^2.0.2
  share_plus: ^4.0.4
  intl: ^0.17.0
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  cloud_firestore: ^4.8.0
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/shapes/
    - lib/data/

  # example:
  fonts:
    - family: SF-Pro-Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Thin.otf
          weight: 200
        - asset: assets/fonts/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Display-Black.otf
          weight: 900
    - family: Next-art
      fonts:
        - asset: assets/fonts/Next-art-Light.otf
          weight: 300
        - asset: assets/fonts/Next-art-Regular.otf
          weight: 400
        - asset: assets/fonts/Next-art-Bold.otf
          weight: 700
        - asset: assets/fonts/Next-art-Heavy.otf
          weight: 900

